version: '3.3'

services: 

    mirror:
        build: .
        command: /epel-mirror/mirror.sh
        volumes:
            - "./mirror.sh:/epel-mirror/mirror.sh:ro"
            - "./mirror:/downloads"

    server:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        restart: always
        command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - "./mirror:/downloads:ro"
        ports:
            - "10081:80"
